#!/usr/bin/python
#
# Copyright (C) 2012 Intel Corporation
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Authors:
#              Tang, Shaofeng <shaofeng.tang@intel.com>


import os
import re
import sys, traceback
import time
import platform
import ctypes
import glob
import ConfigParser
import xml.etree.ElementTree as etree
from optparse import *
from shutil import copyfile
from tempfile import mktemp
from datetime import datetime
from tctshell.plan_options import PlanGeneratorOptions
from tctshell.plan_runner import PlanRunner


def main():
    wrapper = PlanGeneratorOptions()
    wrapper.parse_options(sys.argv)
    output = wrapper.get_output()
    
    runner  = PlanRunner()
    runner.load_local_repo(wrapper.get_repository_folder(), wrapper.get_match_regex(), wrapper.get_command(), wrapper.get_unmatch_regex())

    runner.to_xml(output)

if __name__ == "__main__":
    main()

